name: Secret Scan

on:
  pull_request:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install truffleHog
        run: |
          python3 -m pip install --user truffleHog || true
      - name: Run trufflehog
        run: |
          python3 -m pip show truffleHog >/dev/null 2>&1 || true
          trufflehog filesystem --json . > truffle_report.json || true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: secret-scan
          path: truffle_report.json
      - name: Fail on findings
        run: |
          if [ -s truffle_report.json ]; then echo "Secrets detected"; jq '.results | length' truffle_report.json; exit 1; fi
